# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-21 03:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='lable',
            new_name='label',
        ),
    ]
